spring.application.name=product-service

server.port=8081

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/cloudshop}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${FORMAT_SQL:false}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true