name: CloudShop CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:

  # ==========================================
  # 1. BUILD AND TEST
  # ==========================================
  build-and-test:

    name: Build and Test CloudShop
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16

        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cloudshop

        ports:
          - 5432:5432

        options: >-
          --health-cmd "pg_isready -U postgres -d cloudshop"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 10s

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'
          cache: maven

      # ------------------------------------------
      # Auth Service
      # ------------------------------------------

      - name: Build and test Auth Service
        working-directory: auth-service
        env:
          DB_URL: jdbc:postgresql://localhost:5432/cloudshop
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
        run: mvn -B clean test

      # ------------------------------------------
      # Product Service
      # ------------------------------------------

      - name: Build and test Product Service
        working-directory: product-service
        env:
          DB_URL: jdbc:postgresql://localhost:5432/cloudshop
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
        run: mvn -B clean test

      # ------------------------------------------
      # Order Service
      # ------------------------------------------

      - name: Build and test Order Service
        working-directory: order-service
        env:
          DB_URL: jdbc:postgresql://localhost:5432/cloudshop
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
        run: mvn -B clean test


  # ==========================================
  # 2. DOCKER BUILD
  # ==========================================
  docker-build:

    name: Build CloudShop Docker Images

    needs:
      - build-and-test

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build Auth Service image
        run: |
          docker build \
            -t cloudshop/auth-service:${{ github.sha }} \
            ./auth-service

      - name: Build Product Service image
        run: |
          docker build \
            -t cloudshop/product-service:${{ github.sha }} \
            ./product-service

      - name: Build Order Service image
        run: |
          docker build \
            -t cloudshop/order-service:${{ github.sha }} \
            ./order-service


  # ==========================================
  # 3. SECURITY SCAN
  # ==========================================
  security-scan:

    name: Scan Docker Images with Trivy

    needs:
      - docker-build

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6

      # ------------------------------------------
      # Build images again
      # ------------------------------------------
      #
      # Each GitHub Actions job uses a separate runner.
      # Therefore images from docker-build are not
      # automatically available here.
      #

      - name: Build Auth Service image
        run: |
          docker build \
            -t cloudshop/auth-service:${{ github.sha }} \
            ./auth-service

      - name: Build Product Service image
        run: |
          docker build \
            -t cloudshop/product-service:${{ github.sha }} \
            ./product-service

      - name: Build Order Service image
        run: |
          docker build \
            -t cloudshop/order-service:${{ github.sha }} \
            ./order-service

      # ------------------------------------------
      # Install Trivy
      # ------------------------------------------

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@3fb12ec12f41e471780db15c232d5dd185dcb514
        with:
          version: v0.69.3

      # ------------------------------------------
      # Scan Auth Service
      # ------------------------------------------

      - name: Scan Auth Service
        run: |
          trivy image \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            cloudshop/auth-service:${{ github.sha }}

      # ------------------------------------------
      # Scan Product Service
      # ------------------------------------------

      - name: Scan Product Service
        run: |
          trivy image \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            cloudshop/product-service:${{ github.sha }}

      # ------------------------------------------
      # Scan Order Service
      # ------------------------------------------

      - name: Scan Order Service
        run: |
          trivy image \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            cloudshop/order-service:${{ github.sha }}


  # ==========================================
  # 4. PUBLISH IMAGES TO GHCR
  # ==========================================

  publish-images:

    name: Publish CloudShop Images

    needs:
      - security-scan

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6

      # ------------------------------------------
      # Login to GitHub Container Registry
      # ------------------------------------------

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ------------------------------------------
      # Build Auth Service
      # ------------------------------------------

      - name: Build Auth Service image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/cloudshop-auth-service:${{ github.sha }} \
            ./auth-service

      # ------------------------------------------
      # Build Product Service
      # ------------------------------------------

      - name: Build Product Service image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/cloudshop-product-service:${{ github.sha }} \
            ./product-service

      # ------------------------------------------
      # Build Order Service
      # ------------------------------------------

      - name: Build Order Service image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/cloudshop-order-service:${{ github.sha }} \
            ./order-service

      # ------------------------------------------
      # Push Auth Service
      # ------------------------------------------

      - name: Push Auth Service image
        run: |
          docker push \
            ghcr.io/${{ github.repository_owner }}/cloudshop-auth-service:${{ github.sha }}

      # ------------------------------------------
      # Push Product Service
      # ------------------------------------------

      - name: Push Product Service image
        run: |
          docker push \
            ghcr.io/${{ github.repository_owner }}/cloudshop-product-service:${{ github.sha }}

      # ------------------------------------------
      # Push Order Service
      # ------------------------------------------

      - name: Push Order Service image
        run: |
          docker push \
            ghcr.io/${{ github.repository_owner }}/cloudshop-order-service:${{ github.sha }}